/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package SoetchErrorHandler;

public class SEH {
    public boolean someLibraryMethod() {
        return true;
    }

    public boolean isAlive() {
        return true;
    }

}