/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package SoetchErrorHandler;

import org.junit.Test;
import static org.junit.Assert.*;

public class LibraryTest {
    @Test public void someLibraryMethodReturnsTrue() {
        SEH classUnderTest = new SEH();
        assertTrue("someLibraryMethod should return 'true'", classUnderTest.someLibraryMethod());
        assertTrue("no alive brr", classUnderTest.isAlive());
    }
}
